Files/urls.py
from django.urls import path,include
from Files import views

app_name='Files'

urlpatterns = [
    path('add_file',views.add_file,name="add_file"),
    path('private_file',views.private_file,name="private_file"),
    path('public_file',views.public_file,name="public_file"),
    path('shared_file',views.shared_file,name="shared_file"),
    path('share_submit/<int:pk>',views.share_submit,name="share_submit"),
    

]

bbt_drive_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('Files/',include('Files.urls')),
    path('user/',include('user.urls')),
    path('permissions/',include('permissions.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from user import views

app_name='user'

urlpatterns = [
    path('user',views.user,name="user"),

    path('add_user',views.add_user,name="add_user"),

    path('updateInfo/<int:pk>',views.updateInfo,name="updateInfo"), 

    path('user_delete/<int:pk>',views.user_delete,name="user_delete"), 
]

Files/models.py
from django.db import models

# Create your models here.
class Files(models.Model):
    PUBLIC = 1
    PRIVATE = 2
    FILE_TYPE = (
      (PUBLIC,'public'),
      (PRIVATE,'private'),
    )
    user_id=models.ForeignKey("account.Custom_user", on_delete=models.CASCADE)
    filename=models.CharField( max_length=50)
    filedescription=models.CharField( max_length=500)
    filetype = models.PositiveSmallIntegerField(choices=FILE_TYPE ,default=PUBLIC)
    uploadfile=models.FileField(upload_to='project_files')
    created_at=models.DateTimeField(auto_now=True)
    update_at=models.DateTimeField(auto_now=True)

Files/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from Files.models import Files
from account.models import Member
from permissions.models import Permission
# Create your views here.
def add_file(request):
    Custom_user=request.user
    if request.method == 'POST':
        filename=request.POST['filename']
        filetype=request.POST['filetype']
        filedescription=request.POST['filedescription']
        uploadfile=request.FILES['uploadfile']


        file=Files.objects.create(user_id=Custom_user,
                                        filename=filename,
                                        filetype=filetype,
                                        filedescription=filedescription,
                                        uploadfile=uploadfile) #insert data
        return HttpResponseRedirect(reverse('Files:add_file'))
    else:
        return render(request,'Files/add_file.html')


def public_file(request):
    public_file=Files.objects.all().filter(filetype=1)  #to fetch all record
    date_dict={'public_file':public_file}
    return render(request,"Files/public_file.html",date_dict)

def private_file(request):
    member_object=Member.objects.all()
    private_file=Files.objects.all().filter(filetype=2,user_id=request.user) #to fetch all record
    date_dict={'private_file':private_file ,'member':member_object}
    return render(request,"Files/private_file.html",date_dict)

def shared_file(request):
    member_object=Member.objects.get(custom_user=request.user) #to fetch perticular  records
    permission_object=Permission.objects.all().filter(member=member_object)
    data_dict={'permission_object':permission_object}
    return render(request,"Files/shared_file.html",data_dict)



def share_submit(request,pk):
    File_object=Files.objects.get(pk=pk)
    if request.method == "POST":
        member=request.POST['username']
        member_object=Member.objects.get(pk=member)

        Permission.objects.create(File_object=File_object,
                                  member=member_object)
        
        return HttpResponseRedirect(reverse('Files:private_file'))
    return render(request, "Files/private_file.html")

















# def share(request,pk):
#     if request.method == "POST":
#         member_object=request.POST['username']
#         member=Member.Objects.get(pk=member_object)
#         permission_object=Permission.objects.create(file_object=file_object,
#                                                     member_object=member_object,
#                                                     )
#         return HttpResponseRedirect(reverse('Files:shared_file'))
#     return render(request, "Files/shared_file.html")

templates/Files/add_file.html
{% extends 'account/base.html' %}
{% load static %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}
        <!--   forms start here-->

{% block content %}
            <h2 class="mb-4"> BBT Drive</h2>
            <h3>Add File</h3>
            <form action="{% url 'Files:add_file' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="filename">File Name</label>
                        <input type="text" class="form-control border border-dark" id="Name" placeholder="filename" name='filename'>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="filetype">File Type</label>
                        <select id="filetype" name="filetype" class="form-control border border-dark">
                            <option value=1>Public</option>
                            <option value=2>Private</option>
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="filedescription">File Description</label>
                        <input type="text" class="form-control border border-dark" id="filedescription" placeholder="file description" name='filedescription'>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="exampleFormControlFile1">Upload File</label>
                        <input type="file" class="form-control-file border border-dark" id="exampleFormControlFile1" name="uploadfile">
                    </div>
                </div>

                <center> <button type="submit" class="btn btn-primary">Submit</button></center>
            </form>
{% endblock %}

{% block script %}    
{% endblock %}

{% block extrascript %}
{% endblock %}

templates/Files/private_file.html
{% extends 'account/base.html' %} {% load static %} {% block stylesheets %}
<link
  rel="stylesheet"
  href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css"
/>
<link
  rel="stylesheet"
  href=" https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css"
/>
{% endblock stylesheets %} 
{% block headscript %}
<script
  src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
  integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
  crossorigin="anonymous"></script>
<script
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
  crossorigin="anonymous"></script>
{% endblock headscript %}

<!-- Page Content  -->
{% block content %}
<h2 class="mb-4">BBT Drive Portal</h2>

<h2 class="mb-4">Private Files</h2>

<!--data table-->
<table id="example" class="display" style="width: 100%">
  <thead>
    <tr>
      <th>File Name</th>
      <th>File</th>
      <th>File Type</th>
      <th>Created_at</th>
      <th>updated_at</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for acc in private_file %}
    <tr>
      <td>{{acc.filename}}</td>
      <td>{{acc.filename}}</td>
      {% if acc.filetype == 1 %}
      <td>Public</td>
      {% else %}
      <td>Private</td>
      {% endif %}
      <td>{{acc.created_at}}</td>
      <td>{{acc.update_at}}</td>
      <td>
        <a href="{{acc.uploadfile.url}}" download
          ><button type="button" class="btn btn-info" style="font-size: 12px">
            dowmload
          </button></a
        >
        <button type="button" class="btn btn-info" style="font-size: 12px" data-toggle="modal" data-target="#sharefile{{acc.pk}}">
          <i class="fa fa-share-alt-square" aria-hidden="true"></i>
        </button>
        <!-- Modal -->
        <div
          class="modal fade"
          id="sharefile{{acc.pk}}"
          tabindex="-1"
          role="dialog"
          aria-labelledby="exampleModalCenterTitle"
          aria-hidden="true"
        >
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">
                  share File
                </h5>
                <button
                  type="button"
                  class="close"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
                <div class="modal-body">
                <form action="{% url 'Files:share_submit' acc.pk %}" method="POST">
                {% csrf_token %}
                      <div class="form-group">
                              <label for="username"> username</label>

                              <select class="form-control border border-dark" name="username" id="username">
                              {% for value in member %}
                                  <option value="{{value.pk}}">{{value.custom_user.username}}</option>
                              {% endfor %}
                              </select>

                      </div>
                      <div class="modal-footer">
                          <button
                              type="button"
                              class="btn btn-secondary"
                              data-dismiss="modal"
                              >
                              Close
                          </button>
                          <button 
                              type="submit"
                              class="btn btn-primary">
                              share
                          </button>
                      </div>
                    </form>
                </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %} {% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
{% endblock %} {% block extrascript %}
<script>
  $(document).ready(function () {
    $("#example").DataTable({
      dom: "Bfrtip",
      buttons: [],
    });
  });
</script>
{% endblock %}

templates/Files/public_file.html
{% extends 'account/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<link rel="stylesheet" href=" https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
{% endblock stylesheets %}

{% block headscript %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock headscript %}


{% block content %}
    <h2 class="mb-4"> BBT Drive Portal</h2>

    <h2 class="mb-4"> Public Files</h2>

    <!--data table-->
    <table id="example" class="display" style="width:100%;">
        <thead>
            <tr>
                <th>File Name</th>
                <th>File</th>
                <th>File Type</th>
                <th>Created_at</th>
                <th>updated_at</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for acc in public_file %}
                <tr>
                    <td>{{acc.filename}}</td>
                    <td>{{acc.filename}}</td>
                    {% if acc.filetype == 1 %}
                        <td>Public</td>
                        {% else %}
                        <td>Private</td>
                        {% endif %}
                    <td>{{acc.created_at}}</td>
                    <td>{{acc.update_at}}</td>
                    <td><a href="{{acc.uploadfile.url}}" download><button type="button" class="btn btn-info "style="font-size: 12px;">dowmload</button></a></td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
{% endblock %}

{% block extrascript %}
<script>
    $(document).ready(function() {
        $('#example').DataTable({
            dom: 'Bfrtip',
            buttons: []
        });
    });

</script>
{% endblock %}

templates/Files/shaired_file.html
{% extends 'account/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<link rel="stylesheet" href=" https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
{% endblock stylesheets %}

{% block headscript %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock headscript %}


{% block content %}
    <h2 class="mb-4"> BBT Drive Portal</h2>

    <h2 class="mb-4"> Shared Files</h2>

    <!--data table-->
    <table id="example" class="display" style="width:100%;">
        <thead>
            <tr>
                <th>File Name</th>
                <th>File</th>
                <th>File Type</th>
                <th>Created_at</th>
                <th>updated_at</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for acc in permission_object %}
                <tr>
                    <td>{{acc.File_object.filename}}</td>
                    <td>{{acc.File_object.filedescription}}</td>
                    {% if acc.File_object.filetype == 1 %}
                        <td>Public</td>
                        {% else %}
                        <td>Private</td>
                        {% endif %}
                    <td>{{acc.File_object.created_at}}</td>
                    <td>{{acc.File_object.update_at}}</td>
                    <td><a href="{{acc.File_object.uploadfile.url}}" download><button type="button" class="btn btn-info "style="font-size: 12px;">dowmload</button></a></td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
{% endblock %}

{% block extrascript %}
<script>
    $(document).ready(function() {
        $('#example').DataTable({
            dom: 'Bfrtip',
            buttons: []
        });
    });

</script>
{% endblock %}

templates/Files/shared_file.html
{% extends 'account/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<link rel="stylesheet" href=" https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css">
{% endblock stylesheets %}

{% block headscript %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock headscript %}


{% block content %}
    <h2 class="mb-4"> BBT Drive Portal</h2>

    <h2 class="mb-4"> Shared Files</h2>

    <!--data table-->
    <table id="example" class="display" style="width:100%;">
        <thead>
            <tr>
                <th>File Name</th>
                <th>File</th>
                <th>File Type</th>
                <th>Created_at</th>
                <th>updated_at</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for acc in permission_object %}
                <tr>
                    <td>{{acc.File_object.filename}}</td>
                    <td>{{acc.File_object.filedescription}}</td>
                    {% if acc.File_object.filetype == 1 %}
                        <td>Public</td>
                        {% else %}
                        <td>Private</td>
                        {% endif %}
                    <td>{{acc.File_object.created_at}}</td>
                    <td>{{acc.File_object.update_at}}</td>
                    <td><a href="{{acc.File_object.uploadfile.url}}" download><button type="button" class="btn btn-info "style="font-size: 12px;">dowmload</button></a></td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
{% endblock %}

{% block extrascript %}
<script>
    $(document).ready(function() {
        $('#example').DataTable({
            dom: 'Bfrtip',
            buttons: []
        });
    });

</script>
{% endblock %}